### PR TITLE
enhance rflash upload message

### LINKED ISSUE #4465: [openbmc] rflash tries to upload or active a non-existent tar file
xcat version:
Version 2.13.9 (git commit da902b017c3d9b7e90ac674e8bc6baf7fc31c82a, built Wed Dec  6 06:16:06 EST 2017)

When assigning a non-existent tar file for option ``a`` or ``u``, ``rflash`` tries to upload this bogus file.

Option ``u``:
```
RUN:rflash f6u17 1.tar -u [Thu Dec  7 03:45:35 2017]
ElapsedTime:0 sec
RETURN rc = 1
OUTPUT:
Error: Cannot access /tmp/1.tar. Check the management node and/or service nodes.
Attempting to upload 1.tar, please wait...
CHECK:output =~ Error: Cannot access	[Pass]
CHECK:output !~ Attempting to upload	[Failed]
```

Option ``a``:
```
RUN:rflash f6u17 1.tar -a [Thu Dec  7 03:43:05 2017]
ElapsedTime:0 sec
RETURN rc = 1
OUTPUT:
Error: Cannot access /tmp/1.tar. Check the management node and/or service nodes.
Attempting to upload 1.tar, please wait...
CHECK:output =~ Error: Cannot access	[Pass]
CHECK:output !~ Attempting to upload	[Failed]
```

Option  ``d``
```
RUN:rflash f6u17 --delete 1234567 [Thu Dec  7 04:02:50 2017]
ElapsedTime:1 sec
RETURN rc = 1
OUTPUT:
f6u17: Error: Invalid ID provided to delete.  Use the -l option to view valid firmware IDs.
Attempting to delete ID=1234567, please wait...
CHECK:output =~ Error: Invalid ID provided to delete	[Pass]
CHECK:output !~ Attempting to delete	[Failed]
```

### PR DESCRIPTION
**Pull request by bybai**
fix #4465 

UT messages in:
rflash -u <tar>
rflash -a <tar>
rflash -d </path/to/dir>
rflash -c tar

1, If using valid tar ball and upload, message like:
```
[root@briggs01 xCAT_plugin]# rflash mid05tor12cn16 -u /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar --verbose
mid05tor12cn16: Attempting to upload /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar, please wait ...
```

2, If using invalid tar ball, error message like:
```
[root@briggs01 xCAT_plugin]# rflash mid05tor12cn16 -u /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/withenor.squashfs.tar
Error: Cannot access /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/withenor.squashfs.tar. Check the management node and/or service nodes.
```

3, No "Attempting to upload" messages in ``rflash -c``:
```
[root@briggs01 xCAT_plugin]# XCATBYPASS=1 rflash mid05tor12cn16 -c /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar
DEBUG filename=1, updateid=0, options=-c, invalid= rflash_arguments=/mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar
TAR xyz.openbmc_project.Software.Version.VersionPurpose.Host Firmware Product Version: IBM-witherspoon-ibm-OP9_v1.19_1.83
mid05tor12cn16: BMC Firmware Product:   ibm-v2.0-0-r9-0-gecda565 (Active)*
mid05tor12cn16: HOST Firmware Product:   IBM-witherspoon-ibm-OP9_v1.19_1.83 (Active)*
mid05tor12cn16: HOST Firmware Product: -- additional info: buildroot-2017.08-8-g5e23247
mid05tor12cn16: HOST Firmware Product: -- additional info: capp-ucode-p9-dd2-v2
... ...
```

### CODE REVIEW

File: xCAT-server/lib/xcat/plugins/openbmc.pm [hunk 1]
```diff
@@ -1102,7 +1102,6 @@ sub parse_args {
             if ($option_flag !~ /^-c$|^--check$|^-u$|^--upload$|^-a$|^--activate$/) {
                 return ([ 1, "Invalid option specified when a file is provided: $option_flag" ]);
             }
-            xCAT::SvrUtils::sendmsg("Attempting to upload $flash_arguments[0], please wait...", $callback);
```
Comment (gurevichmark) [inline xCAT-server/lib/xcat/plugins/openbmc.pm]: I think this message should stay or its display be conditional. The idea was that this message will be displayed only once for the range of nodes and will indicate to the user that command has started. This way if nodes are not accessible or took a long time to respond, user would not think the command has hung.

**Comment by chenglch** [comment]
If the message for all of the nodes can be displayed like `<node>: <message>`, I support this kind of fix. If some problem happens, the error message should be displayed like `<node>:<error message>`. 
I don't know if our current code could achieve this.

**Comment by bybai** [comment]
Hi @chenglch and @gurevichmark,
If there is tar file exist, this message will be displayed only once for the range of nodes, like: "Attempting to upload xxx.tar, please wait...";
If there is no tar file exist or cannot read, the error message will be displayed overall, not for specific node, like "Error: Cannot access /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/withenor.squashfs.tar.".
If there is tar file exist, and enter upload file request, there is uploading or error message for each node, normal message like "mid05tor12cn02: Uploading /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar ...". error message like ""Failed to upload update file $file :" . $h->{message} . " - " . $h->{data}->{description}".

The **issue** is : 1, the location of "Attempting to upload $flash_arguments[0], please wait..." is wrong in code as #4465 described. 2, and after I add "-d" option,  the massage should cover both bmc+pnor tar files. so I changed this message location in code.

UT covered:
```
rflash -u
rflash -a
rflash -d </path/to/dir>
rflash -c tar
```

case for error message like:
```
[root@briggs01 xCAT_plugin]# rflash mid05tor12cn16 -u squashfs.tar
Error: Cannot access /opt/xcat/lib/perl/xCAT_plugin/squashfs.tar. Check the management node and/or service nodes.
```
case for normal message like:
```
[root@briggs01 xCAT_plugin]# rflash mid05tor12cn16,mid05tor12cn02 -u /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar --verbose
Attempting to upload /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar, please wait...
mid05tor12cn02: Uploading /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar ...
mid05tor12cn16: Uploading /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/witherspoon.pnor.squashfs.tar ...
mid05tor12cn16: Firmware upload successful. Use -l option to list.
mid05tor12cn02: Firmware upload successful. Use -l option to list.
```

File: xCAT-server/lib/xcat/plugins/openbmc.pm (hunk 1 above)
Comment (bybai) [reply xCAT-server/lib/xcat/plugins/openbmc.pm]: I polished this in new commit.

**Comment by whowutwut** [comment]
When we merge, please try to associate the labels and milestones,  It comes in extra handy when we are trying to come up with a changelog or scrutinize the changes that go into a target build/release.  Thanks!
