### PR TITLE
fix #1431 Can't find expected logs in MN for ubuntu14.04.4 ppc64le

### LINKED ISSUE #1431: [FVT]Can't find expected logs in MN for ubuntu14.04.4 ppc64le
Using latest daily build to install CN with ubuntu14.04.4 diskless, then try to find logs in MN:/var/log/xcat/computes.log when xcatdebugmode=1/2, but below log failed to be shown.
```
RUN:cat /var/log/xcat/computes.log | grep "running /opt/xcat/xcatdsklspost"

[cat /var/log/xcat/computes.log | grep "running /opt/xcat/xcatdsklspost"] Running Time:0 sec
RETURN: rc = 1
OUTPUT:
CHECK:output =~ running /opt/xcat/xcatdsklspost [Failed]
```

### PR DESCRIPTION
**Pull request by penguhyang**
fix #1431 
 enable the log can be forwarded to mn

### CODE REVIEW

**Comment by immarvin** [comment]
since xcatdsklspost is called on ``service xcatpostinit start``, maybe you should try to add ``syslog`` service as a prerequisite for xcatpostinit service

**Comment by daniceexi** [comment]
@immarvin Has ``syslog`` service been installed in the osimage? Do you suggest @penguhyang to enable it before running postscript?

**Comment by immarvin** [comment]
hi @daniceexi , the logs mentioned in the issue are generated on the running of postbootscripts in "init" process inside rootimg. Since syslog is installed in the rootimg and the ``syslog`` postscript is enabled during ``genimage`` and ``packimage``, the syslog service should have been started at the time.

**Comment by daniceexi** [comment]
@immarvin so your idea is to add syslog as a dependency for xcatinit, right?

**Comment by immarvin** [comment]
hi @daniceexi , yes. @penguhyang is trying on this

File: xCAT/postscripts/xcatlib.sh [hunk 1]
```diff
@@ -761,7 +761,15 @@ function msgutil_r {
 
 
    if [ -n "$logserver" ];then
-      logger -n $logserver -t xcat -p local4.$msgtype "$msgstr" >/dev/null 2>&1
+        if [ -f /etc/os-release ] && cat /etc/os-release |grep NAME|grep Ubuntu>/dev/null
+        then
+            str_id=`logger -V | awk '{print $4}' | awk -F '.' '{print $2}'`
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: if the issue only exists on rsyslog "2.20.x", the version should be matched more accurate

**Comment by immarvin** [comment]
more comments needed

File: xCAT/postscripts/xcatlib.sh [hunk 2]
```diff
@@ -761,7 +761,15 @@ function msgutil_r {
...
+            if [ $str_id -gt 20  ]; then
```
Comment (daniceexi) [inline xCAT/postscripts/xcatlib.sh]: Before using $str_id, you should check whether it's empty.

File: xCAT/postscripts/xcatlib.sh (hunk 1 above)
Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed.

File: xCAT/postscripts/xcatlib.sh (hunk 2 above)
Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed.

File: xCAT/postscripts/xcatlib.sh [hunk 3]
```diff
@@ -761,7 +761,30 @@ function msgutil_r {
 
 
    if [ -n "$logserver" ];then
-      logger -n $logserver -t xcat -p local4.$msgtype "$msgstr" >/dev/null 2>&1
+        # Ubuntu 14.04.4 use version 2.20.1
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]:
````
#In Ubuntu, there is a bug in some logger version that "-n" is ignored. The workaround is to specify the 
#"-u <some dummy file>"  option together with "-n"  option. 
#So far as we know, this bug exists in logger 2.20 shipped in ubuntu 14.04.4 and
#has been fixed in logger 2.25 shipped in ubuntu 15.10. Since "-u" option won't break anything,
#use "-u xxxx" for the logger versions under 2.25  
````

File: xCAT/postscripts/xcatlib.sh [hunk 4]
```diff
@@ -761,7 +761,30 @@ function msgutil_r {
...
+        # It builds fine but ignores the -n switch just like the installed version.
+        if [ -f /etc/os-release ] && cat /etc/os-release |grep NAME|grep Ubuntu>/dev/null
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: use ``grep -i``

File: xCAT/postscripts/xcatlib.sh (hunk 3 above)
Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed.

File: xCAT/postscripts/xcatlib.sh (hunk 4 above)
Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed.

File: xCAT/postscripts/xcatlib.sh [hunk 5]
```diff
@@ -761,7 +761,33 @@ function msgutil_r {
 
 
    if [ -n "$logserver" ];then
-      logger -n $logserver -t xcat -p local4.$msgtype "$msgstr" >/dev/null 2>&1
+       #In Ubuntu, there is a bug in some logger version that "-n" is ignored. The workaround is to specify the 
+       #"-u <some dummy file>"  option together with "-n"  option.
+       #So far as we know, this bug exists in logger 2.20 shipped in ubuntu 14.04.4 and
+       #has been fixed in logger 2.25 shipped in ubuntu 15.04. Since "-u" option won't break anything,
+       #use "-u xxxx" for the logger versions under 2.25
+        if [ -f /etc/os-release ] && cat /etc/os-release |grep -i NAME|grep -i Ubuntu>/dev/null
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: > /dev/null 2>&!

Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed.

File: xCAT/postscripts/xcatlib.sh [hunk 6]
```diff
@@ -761,7 +761,33 @@ function msgutil_r {
...
    if [ -n "$logserver" ];then
-      logger -n $logserver -t xcat -p local4.$msgtype "$msgstr" >/dev/null 2>&1
+       #In Ubuntu, there is a bug in some logger version that "-n" is ignored. The workaround is to specify the 
+       #"-u <some dummy file>"  option together with "-n"  option.
+       #So far as we know, this bug exists in logger 2.20 shipped in ubuntu 14.04.4 and
+       #has been fixed in logger 2.25 shipped in ubuntu 15.04. Since "-u" option won't break anything,
+       #use "-u xxxx" for the logger versions under 2.25
+        if [ -f /etc/os-release ] && cat /etc/os-release |grep -i NAME|grep -i Ubuntu>/dev/null 2>&1
+        then
+            str_ver=`logger -V | awk '{print $4}' | awk -F '.' '{print $1}'`
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: ``logger -V`` will run twice, it should be only run 1 time.

File: xCAT/postscripts/xcatlib.sh [hunk 7]
```diff
@@ -761,7 +761,33 @@ function msgutil_r {
...
+            if [ "$?" != "0" ];then
+                echo "Error happens to get logger version!"
+            fi
+            if [ $str_ver -eq 2 ]; then
+                str_id=`logger -V | awk '{print $4}' | awk -F '.' '{print $2}'`
+                if [ "$?" != "0" ];then
+                    echo "Error happens to get logger version!"
+                fi
+                if [ $str_id -gt 25 ]; then
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: you only need to use "-u" for the condition [ubuntu && logger version<=25], why so many branches? please reorg the loop logic

File: xCAT/postscripts/xcatlib.sh (hunk 6 above)
Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed.

File: xCAT/postscripts/xcatlib.sh [hunk 8]
```diff
@@ -761,7 +761,25 @@ function msgutil_r {
...
    if [ -n "$logserver" ];then
-      logger -n $logserver -t xcat -p local4.$msgtype "$msgstr" >/dev/null 2>&1
+       #In Ubuntu, there is a bug in some logger version that "-n" is ignored. The workaround is to specify the 
+       #"-u <some dummy file>"  option together with "-n"  option.
+       #So far as we know, this bug exists in logger 2.20 shipped in ubuntu 14.04.4 and
+       #has been fixed in logger 2.25 shipped in ubuntu 15.04. Since "-u" option won't break anything,
+       #use "-u xxxx" for the logger versions under 2.25
+        if [ -f /etc/os-release ] && cat /etc/os-release |grep -i NAME|grep -i Ubuntu>/dev/null 2>&1
+        then
+            str_ver=`logger -V | awk '{print $4}' | awk -F '.' '{print $1 $2}'`
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: if the ``looger -V`` returns "logger from util-linux 3.1", will the logic work as expected?

Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed.

File: xCAT/postscripts/xcatlib.sh [hunk 9]
```diff
@@ -761,7 +761,25 @@ function msgutil_r {
...
    if [ -n "$logserver" ];then
-      logger -n $logserver -t xcat -p local4.$msgtype "$msgstr" >/dev/null 2>&1
+       #In Ubuntu, there is a bug in some logger version that "-n" is ignored. The workaround is to specify the 
+       #"-u <some dummy file>"  option together with "-n"  option.
+       #So far as we know, this bug exists in logger 2.20 shipped in ubuntu 14.04.4 and
+       #has been fixed in logger 2.25 shipped in ubuntu 15.04. Since "-u" option won't break anything,
+       #use "-u xxxx" for the logger versions under 2.25
+        if [ -f /etc/os-release ] && cat /etc/os-release |grep -i NAME|grep -i Ubuntu>/dev/null 2>&1
+        then
+            eval $(logger -V | awk '{print $4}' | awk -F '.' '{printf("var1=%s; var2=%s",$1,$2)}')
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: better be ``eval $(logger -V 2>/dev/null  ...``

File: xCAT/postscripts/xcatlib.sh [hunk 10]
```diff
@@ -761,7 +761,25 @@ function msgutil_r {
...
+            if [ "$?" != "0" ];then
```
Comment (immarvin) [inline xCAT/postscripts/xcatlib.sh]: no need to check the return value.

File: xCAT/postscripts/xcatlib.sh (hunk 9 above)
Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed

File: xCAT/postscripts/xcatlib.sh (hunk 10 above)
Comment (penguhyang) [inline xCAT/postscripts/xcatlib.sh]: fixed

**Comment by immarvin** [comment]
agree tp merge
