### PR TITLE
fix sles11.4 packimage return error when use tar compress method

### LINKED ISSUE #1742: [FVT]:packimage -m tar -c gzip failed on sles11.4
xCAT 2.12.2 8/17 build on sles11.4 ppc64
```
c910f02c01p14:/opt/xcat/share/xcat/tools/autotest/result # packimage sles11.4-ppc64-netboot-compute -m tar -c gzip
Packing contents of /install/netboot/sles11.4/ppc64/compute/rootimg
archive method:tar
compress method:gzip
tar: unrecognized option '--selinux'
Try `tar --help' or `tar --usage' for more information.

Error: packimage failed while running:
 cat /tmp/xcat_packimg.12131| tar --selinux --no-recursion --use-compress-program=gzip -T - -cf  ../rootimg.tar.gz
```

### PR DESCRIPTION
**Pull request by penguhyang**
sles11.4 tar not support --selinux --xattrs-include options
fix #1742

### CODE REVIEW

File: xCAT-server/lib/xcat/plugins/packimage.pm [hunk 1]
```diff
@@ -492,24 +492,38 @@ sub process_request {
         $oldmask = umask 0077;
     } elsif ($method =~ /tar/) {
         if (!$exlistloc) {
-            my $checkoption = `tar --xattrs-include 2>&1`;
-            if ($checkoption =~ /unrecognized/) {
-                $excludestr = "find . -xdev -print0 | tar --selinux --no-recursion --use-compress-program=$compress --null -T - -cf ../rootimg.$suffix";
+            my $checkoption1 = `tar --xattrs-include 2>&1`;
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: the logic from line#495 to line#524 should be moved to line#494, it should be outside the if-else  
 on exlistloc

Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: fixed.

**Comment by immarvin** [comment]
agree to merge
