### PR TITLE
enhance packimage -m txc

### LINKED ISSUE #922: [CUSTOMER] Ping not working for non root users on Diskless PowerKVM guests (rhels7.2)
Hi, 
I've been playing with provisioning Diskless VM guests on PowerKVM and I ran into a bit of a problem. When I ssh into the guest and attempt to ping as a user my user is denied access to the ping command. This issue is resolved when I change permissions for /bin/ping, but it seems to represent an underlying permissions issue that I can't quite source. As far as I can tell SELinux is disabled on both the xcat master and guest nodes.

Thanks,
John

> [root@localhost ~]# ping 10.4.4.24
> PING 10.4.4.24 (10.4.4.24) 56(84) bytes of data.
> 64 bytes from 10.4.4.24: icmp_seq=1 ttl=64 time=0.152 ms
> 64 bytes from 10.4.4.24: icmp_seq=2 ttl=64 time=0.106 ms
> 64 bytes from 10.4.4.24: icmp_seq=3 ttl=64 time=0.060 ms
> ^C
> --- 10.4.4.24 ping statistics ---
> 3 packets transmitted, 3 received, 0% packet loss, time 1998ms
> rtt min/avg/max/mdev = 0.060/0.106/0.152/0.037 ms
>[root@localhost ~]# su - jdunham
> [jdunham@localhost ~]# ping 10.4.4.24
> ping: icmp open socket: Operation not permitted
> [jdunham@localhost ~]# exit
> [root@localhost ~]# chmod u+s /bin/ping
> [root@localhost ~]# su - jdunham
> Last login: Wed Apr 13 14:58:49 UTC 2016 on pts/0
> [jdunham@localhost ~]# ping 10.4.4.24
> PING 10.4.4.24 (10.4.4.24) 56(84) bytes of data.
> 64 bytes from 10.4.4.24: icmp_seq=1 ttl=64 time=0.447 ms
> 64 bytes from 10.4.4.24: icmp_seq=2 ttl=64 time=0.097 ms
> ^C
> --- 10.4.4.24 ping statistics ---
> 2 packets transmitted, 2 received, 0% packet loss, time 999ms
> rtt min/avg/max/mdev = 0.097/0.272/0.447/0.175 ms

### PR DESCRIPTION
**Pull request by penguhyang**
1 use gzip instead of xz to improve the compress speed.(will try to use pigz first, if pigz not available then use gzip)
```
[root@c910f03c17k14 compute]# echo `date`;packimage -m txc rhels7.2-ppc64le-netboot-compute;echo `date`
Thu Jul 28 04:50:52 EDT 2016
Packing contents of /install/netboot/rhels7.2/ppc64le/compute/rootimg
compress method:txc
Thu Jul 28 04:51:37 EDT 2016
```
```
[root@c910f03c17k14 compute]# ls -al rootimg.txz
-rw-r--r-- 1 root root 295053947 Jul 28 04:51 rootimg.txz
```
2 fix #922
3 change -m txc to -m tar

### CODE REVIEW

File: xCAT-server/lib/xcat/plugins/packimage.pm [hunk 1]
```diff
@@ -445,16 +445,15 @@ sub process_request {
             $callback->({ error => ["Command xz does not exist, please make sure it works."] });
             return 1;
         }
-        $callback->({ info => ["It will take several minutes to complete. So please wait for several minutes, then the other operations could be done. Otherwise, the other operation will fail."] });
         if (!$exlistloc) {
-            $excludestr = "find . -xdev | tar --selinux --xattrs-include='*' -T - -Jcvf ../rootimg.txz";
+            $excludestr = "find . -xdev | tar --selinux --xattrs-include='*' -T - -zcvf ../rootimg.txz";
```
Comment (neo954) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: The ``tar`` argument ``-J`` means do the compression with ``xz``. If you decide to use ``-z``, which means do the compression with ``gzip``, please use the file extension name ``.tgz`` instead of ``.txz``. The file extension name does have some meanings. Please take care of it.

Comment (neo954) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: When you use ``tar -T -`` with ``find``. Please consider use ``-print0`` of ``find`` and ``--null`` of ``tar``. In this way, you can handle file names with space characters, ``'\t'`` characters and ``'\n'`` characters.

For example

    find . -xdev -print0 | tar --selinux --xattrs-include='*' --null -T - -zcvf ../rootimg.tgz

File: xCAT-server/lib/xcat/plugins/packimage.pm [hunk 2]
```diff
@@ -445,16 +445,15 @@ sub process_request {
             $callback->({ error => ["Command xz does not exist, please make sure it works."] });
```
Comment (neo954) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: If you do not use command ``xz``. Do not do command checking of ``xz`` here.

File: xCAT-server/share/xcat/netboot/rh/dracut/install.netboot [hunk 3]
```diff
@@ -1,6 +1,6 @@
 #!/bin/sh
 echo $drivers
-dracut_install wget tar xz cpio gzip dash modprobe touch echo cut wc xz
+dracut_install wget tar xz cpio gzip dash modprobe touch echo cut wc
```
Comment (neo954) [inline xCAT-server/share/xcat/netboot/rh/dracut/install.netboot]: ``xz`` still appeared in this line.

File: xCAT-server/lib/xcat/plugins/packimage.pm (hunk 1 above)
Comment (neo954) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: Even for ``cpio``, you can handle this kind of problem with ``cpio -0``. For example in line 432 and 439. I know it is not your problem. But you can handle it as well.

Comment (neo954) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: Even for ``cpio``, you can handle this kind of problem with ``cpio -0``. For example in line 432 and 439. I know it is not your problem. But you can handle it w

**Comment by neo954** [comment]
If you decide use ``gzip`` instead of ``xz``. Please do not call the name of packaging method ``txz`` any more. You may call it ``tgz``. The name does have some meanings. Please take care of it as well.

File: xCAT-server/lib/xcat/plugins/packimage.pm (hunk 2 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: fixed.

File: xCAT-server/share/xcat/netboot/rh/dracut/install.netboot (hunk 3 above)
Comment (penguhyang) [inline xCAT-server/share/xcat/netboot/rh/dracut/install.netboot]: fixed.

File: xCAT-server/lib/xcat/plugins/packimage.pm (hunk 1 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/packimage.pm]: fixed

**Comment by immarvin** [comment]
please do not forget to update the pkglist for sles11 and redhat6 and "genimage" for sles11.

**Comment by immarvin** [comment]
currently the manpage for "packimage -m" is:
````
       -m          Method (cpio,txc,squashfs, default is cpio)
````

should better to be 
````
       -m          Archive Method (cpio,tar,squashfs, default is cpio)
````

**Comment by immarvin** [comment]
agree to merge

**Comment by daniceexi** [comment]
Great change. 👍

**Comment by daniceexi** [comment]
@caomengmeng You can start your test work for this change.
