### PR TITLE
confignetwork error message enhancement 

### LINKED ISSUE #3704: confignetwork error message enhancement
From Victor's comments:
1. Going though the `confignetwork` and we see some new error messages, not able to really tell...

```sn02: [E]: Error: enP52p1s0f0 enP52p1s0f0 pair is invalid nic and nicdevice pair.
sn02: [E]: Error: enp1s0f0 enp1s0f0 pair is invalid nic and nicdevice pair.

```
Turns out what this means is that we should not define the `nicdevices.enP52p1s0f0`... can we make that error message more clear? We figured it out by playing with the options

2. This message should have `Error` .. so we can see it easily... and be consistent

```
sn02: [E]: configeth on sn02: Network object cn is not defined.

```
should be `[E]: Error:`

### PR DESCRIPTION
**Pull request by bybai**
fix #3704

### CODE REVIEW

File: xCAT/postscripts/confignetwork [hunk 1]
```diff
@@ -406,12 +406,12 @@ function sort_nics_device_order {
...
                 fi
             else
-                echo "Error: $nic_dev $base_nic_dev pair is invalid nic and nicdevice pair."
+                echo "Error: nicdevices.$nic_dev base nic device cannot be $base_nic_type $base_nic_dev.(nicdevices is only required on vlan/bond/bridge)"
             fi
             ((num+=1))
         done
       else
-        log_error "Error: only support configure bond/vlan/bridge on redhat."
+        log_error "only support configure bond/vlan/bridge on redhat."
```
Comment (whowutwut) [inline xCAT/postscripts/confignetwork]: Should format this: 
`Configuration of Bond/VLAN/Bridge on Red Hat."

File: xCAT/postscripts/confignetwork [hunk 2]
```diff
@@ -406,12 +406,12 @@ function sort_nics_device_order {
                     vlan_slot=$vlan_slot" "$num
                 fi
             else
-                echo "Error: $nic_dev $base_nic_dev pair is invalid nic and nicdevice pair."
+                echo "Error: nicdevices.$nic_dev base nic device cannot be $base_nic_type $base_nic_dev.(nicdevices is only required on vlan/bond/bridge)"
```
Comment (whowutwut) [inline xCAT/postscripts/confignetwork]: Should format: `Bond/VLAN/Bridge` and in the same order as other messages.  Perhaps this should be a variable so out output messages are consistent.

Comment (whowutwut) [inline xCAT/postscripts/confignetwork]: I think we also need some punctuation to help readability... Can you show me the output message?  

Seems like there should be some period between `...$base_nic_type. $base_nic_dev.(nicdevices ...`

File: xCAT/postscripts/confignetwork [hunk 3]
```diff
@@ -555,7 +555,7 @@ function configure_nicdevice {
                 errorcode=1
             fi
         else
-            log_error "Error : please check nic data in nics table."
+            log_error "please check nic data in nics table."
```
Comment (whowutwut) [inline xCAT/postscripts/confignetwork]: I always try to avoid using "Please and Thank you" in the messages....

`Check the NIC data in the 'nics' table.`   I capitalized NIC because it stands for Network Interface Card, but 'nics' is an xCAT table name..

File: xCAT/postscripts/nicutils.sh [hunk 4]
```diff
@@ -1473,7 +1473,7 @@ function create_bond_interface {
     wait_for_ifstate $ifname UP 200 1
     rc=$?
     if [ $rc -ne 0 ]; then
-        log_error "Error! Interface \"$ifname\" was NOT in \"UP\" state eventually."
+        log_error "Interface \"$ifname\" was NOT in \"UP\" state eventually."
```
Comment (whowutwut) [inline xCAT/postscripts/nicutils.sh]: Suggest change in the message: 

Interface " " could not be brought to "UP" state.

**Comment by whowutwut** [comment]
Is it possible to provide the updatenode output when we run the new scripts. This way we can see the external messages... at least for the success case?

**Comment by bybai** [comment]
Hi @whowutwut ,
I updated code based on your comments.
I cut `updatenode` log from autotest cases:
```
RUN:chdef bybc0609  nicnetworks.eth2.6="60_0 _0_0-255_0_0_0" nicnetworks.eth2.7="70_0 _0_0-255_0_0_0" nictypes.eth2.6=vlan nictypes.eth2.7=vlan nicips.eth2.6=60.5.106.9 nicips.eth2.7=70.5.106.9 nicdevices.eth2.6=eth2.6 nicdevices.eth2.7=eth2.7 [Thu Aug 24 04:39:16 2017]
ElapsedTime:1 sec
RETURN rc = 0
OUTPUT:
1 object definitions have been created or modified.

RUN:updatenode bybc0609 -P confignetwork [Thu Aug 24 04:39:17 2017]
ElapsedTime:2 sec
RETURN rc = 1
OUTPUT:
bybc0609: xcatdsklspost: downloaded postscripts successfully
bybc0609: Thu Aug 24 08:39:27 UTC 2017 Running postscript: confignetwork
bybc0609: [E]:Error: nicdevices.eth2.6 base nic device cannot be vlan eth2.6.(nicdevices is only required on Bond/VLAN/Bridge)
bybc0609: [E]:Error: nicdevices.eth2.7 base nic device cannot be vlan eth2.7.(nicdevices is only required on Bond/VLAN/Bridge)
bybc0609: [I]: NetworkManager is inactive.
bybc0609: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
bybc0609: configure nic and its device :
bybc0609: [E]:Error: Check the NIC data in the 'nics' table.
bybc0609: postscript: confignetwork exited with code 1
bybc0609: Running of postscripts has completed.
```

File: xCAT/postscripts/confignetwork [hunk 5]
```diff
@@ -406,12 +406,12 @@ function sort_nics_device_order {
...
                 fi
             else
-                echo "Error: $nic_dev $base_nic_dev pair is invalid nic and nicdevice pair."
+                echo "Error: nicdevices.$nic_dev base nic device cannot be $base_nic_type $base_nic_dev.(nicdevices is only required on Bond/VLAN/Bridge)"
             fi
             ((num+=1))
         done
       else
-        log_error "Error: only support configure bond/vlan/bridge on redhat."
+        log_error "only support configuration of Bond/VLAN/Bridge on Red Hat."
```
Comment (whowutwut) [inline xCAT/postscripts/confignetwork]: Can we make O capital?

File: xCAT/postscripts/nicutils.sh [hunk 6]
```diff
@@ -1473,7 +1473,7 @@ function create_bond_interface {
     wait_for_ifstate $ifname UP 200 1
     rc=$?
     if [ $rc -ne 0 ]; then
-        log_error "Error! Interface \"$ifname\" was NOT in \"UP\" state eventually."
+        log_error "Interface \"$ifname\" could not be brought to \"UP\"."
```
Comment (whowutwut) [inline xCAT/postscripts/nicutils.sh]: Suggest removing "to"  => `could not be brought "UP".`

**Comment by zet809** [comment]
Hi, @whowutwut , I merge this PR to have it included in dev build tonight.
