### PR TITLE
fix issue 3430 confignetwork could not config network if MTU is not set

### LINKED ISSUE #3430: [FVT]:confignetwork could not config network if MTU is not set
xCAT 2.13.5
```
# lsxcatd -v
Version 2.13.6 (git commit 1f277339e940108e71dd7f96961820f5c5ad5e55, built Mon Jul 10 06:15:38 EDT 2017)
```

1. config nics and networks table.
```
[root@c910f02c01p22 /]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","eth1","10.0.0.103",,"10.2.1.22",,,,,,,,,,,,,
"autotest_ent","192.168.10.0","255.255.255.0",,"192.168.10.3",,,,,,,,,,,,,,,
"testnetwork","100.100.100.0","255.255.255.0","!remote!eth0","100.100.100.1",,,,,,,,,,,,,,,
"11_1_0_0-255_255_0_0","11.1.0.0","255.255.0.0","eth2",,,,,,,,,,,,,,,,
"12_1_0_0-255_255_0_0","12.1.0.0","255.255.0.0","eth0",,,,,,,,,,,,,,,,
"30_5_0_0-255_255_0_0","30.5.0.0","255.255.0.0",,,,,,,,,,,,,,,,,
"40_5_0_0-255_255_0_0","40.5.0.0","255.255.0.0",,,,,,,,,,,,,,,,,
[root@c910f02c01p22 /]# tabdump nics
#node,nicips,nichostnamesuffixes,nichostnameprefixes,nictypes,niccustomscripts,nicnetworks,nicaliases,nicextraparams,nicdevices,nicsadapter,comments,disable
"c910f02c01p23","bond0.3!40.5.106.8,eth2!11.1.0.100,bond0.2!30.5.106.8,eth0!12.1.0.100",,,"bond0.3!vlan,eth2!ethernet,bond0.2!vlan,bond0!bond,eth0!ethernet",,"bond0.3!40_5_0_0-255_255_0_0,eth2!11_1_0_0-255_255_0_0,bond0.2!30_5_0_0-255_255_0_0,eth0!12_1_0_0-255_255_0_0",,,"bond0.3!bond0,bond0.2!bond0,bond0!eth2|eth0",,,
```
2. run updatenode -P confignetwork and get the error
```
c910f02c01p23: [I]: create_persistent_ifcfg ifname=eth0 inattrs=ONBOOT=yes,NM_CONTROLLED=no,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none,MTU=[E]: Fail to get "" for network "mtu"
c910f02c01p23: ./nicutils.sh: line 437: Fail: command not found
```

### PR DESCRIPTION
**Pull request by bybai**
fix #3430 
Unit test:
```
[root@bybc0602 postscripts]# updatenode bybc0609 confignetwork
bybc0609: xcatdsklspost: downloaded postscripts successfully
bybc0609: Fri Jul 14 02:10:35 EDT 2017 Running postscript: confignetwork
bybc0609: [I]: All valid nics and device list:
bybc0609: [I]: bond0 eth2@eth3
bybc0609: [I]: NetworkManager is inactive.
bybc0609: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
bybc0609: configure nic and its device : bond0 eth2@eth3
bybc0609: [I]: create_bond_interface ifname=bond0 slave_ports=eth2,eth3
bybc0609: [I]: Pickup xcatnet, "30_5_0_0-255_255_0_0", from NICNETWORKS for interface "bond0".
bybc0609: [W]: There is no mtu value configured in network 30_5_0_0-255_255_0_0 from networks table. -----> here is to check if there is mtu value in networks table
bybc0609: [I]: ip link set bond0 down
bybc0609: [I]: [bond.down] >> 18: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
bybc0609: [I]: [bond.down] >>     link/ether 5a:6b:07:73:37:db brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: [bond.slavesAft] >>
bybc0609: [I]: ip link set eth2 down
bybc0609: [I]: [slave]: >> 4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
bybc0609: [I]: [slave]: >>     link/ether 42:47:0a:05:6a:09 brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: create_persistent_ifcfg ifname=eth2 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
bybc0609: ['ifcfg-eth2']
bybc0609: [I]: >> DEVICE="eth2"
bybc0609: [I]: >> BOOTPROTO="none"
bybc0609: [I]: >> NAME="eth2"
bybc0609: [I]: >> ONBOOT="yes"
bybc0609: [I]: >> USERCTL="no"
bybc0609: [I]: >> TYPE="Ethernet"
bybc0609: [I]: >> SLAVE="yes"
bybc0609: [I]: >> MASTER="bond0"
bybc0609: [I]: ip link set eth3 down
bybc0609: [I]: [slave]: >> 5: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
bybc0609: [I]: [slave]: >>     link/ether 42:82:0a:05:6a:09 brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: create_persistent_ifcfg ifname=eth3 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
bybc0609: ['ifcfg-eth3']
bybc0609: [I]: >> DEVICE="eth3"
bybc0609: [I]: >> BOOTPROTO="none"
bybc0609: [I]: >> NAME="eth3"
bybc0609: [I]: >> ONBOOT="yes"
bybc0609: [I]: >> USERCTL="no"
bybc0609: [I]: >> TYPE="Ethernet"
bybc0609: [I]: >> SLAVE="yes"
bybc0609: [I]: >> MASTER="bond0"
bybc0609: [I]: [bond.slavesNew] >> eth2 eth3
bybc0609: [I]: ip link set bond0 up
bybc0609: [I]: [ip.link] >> 18: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT qlen 1000
bybc0609: [I]: [ip.link] >>     link/ether 42:47:0a:05:6a:09 brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: create_persistent_ifcfg ifname=bond0 xcatnet=30_5_0_0-255_255_0_0 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Bond,BONDING_MASTER=yes,BONDING_OPTS='mode=802.3ad miimon=100',BOOTPROTO=none,DHCLIENTARGS='-timeout 200'
bybc0609: [W]: There is no mask configure in network 30_5_0_0-255_255_0_0 from networks table.      -----------> here is to check if there is mask in networks table
bybc0609: [W]: There is no mtu value configured in network 30_5_0_0-255_255_0_0 from networks table. ----------> here is to check if there is mtu in networks table
bybc0609: ['ifcfg-bond0']
bybc0609: [I]: >> DEVICE="bond0"
bybc0609: [I]: >> BOOTPROTO="none"
bybc0609: [I]: >> IPADDR="30.5.106.9"
bybc0609: [I]: >> NAME="bond0"
bybc0609: [I]: >> BONDING_MASTER="yes"
bybc0609: [I]: >> ONBOOT="yes"
bybc0609: [I]: >> USERCTL="no"
bybc0609: [I]: >> TYPE="Bond"
bybc0609: [I]: >> BONDING_OPTS="mode=802.3ad miimon=100"
bybc0609: [I]: >> DHCLIENTARGS="-timeout 200"
bybc0609: postscript: confignetwork exited with code 0
bybc0609: Running of postscripts has completed.
```
The point is 
```
... ...
bybc0609: [W]: There is no mtu value configured in network 30_5_0_0-255_255_0_0 from networks table. ----------> here is to check if there is mtu in networks table
... ...
bybc0609: [W]: There is no mask configure in network 30_5_0_0-255_255_0_0 from networks table.      -----------> here is to check if there is mask in networks table
bybc0609: [W]: There is no mtu value configured in network 30_5_0_0-255_255_0_0 from networks table. ----------> here is to check if there is mtu in networks table
... ...
```

### CODE REVIEW

File: xCAT/postscripts/nicutils.sh [hunk 1]
```diff
@@ -496,11 +497,19 @@ function create_persistent_ifcfg {
         fi
         if [ -z "$_netmask" ]; then
             _netmask=`get_network_attr $xcatnet mask`
+            if [ $? -ne 0 ]; then
+                log_warn "There is no mask configure in network $xcatnet from networks table."
```
Comment (robin2008) [inline xCAT/postscripts/nicutils.sh]: "There is no netmask configured for network $xcatnet in networks table."

File: xCAT/postscripts/nicutils.sh [hunk 2]
```diff
@@ -496,11 +497,19 @@ function create_persistent_ifcfg {
...
+                _netmask=""
+            fi
         fi
 
         # Query mtu value from "networks" table
         if [ -z "$_mtu" ]; then
             _mtu=`get_network_attr $xcatnet mtu`
+            if [ $? -ne 0 ]; then
+                log_warn "There is no mtu value configured in network $xcatnet from networks table."
```
Comment (robin2008) [inline xCAT/postscripts/nicutils.sh]: There is no MTU configured for network $xcatnet in networks table.

**Comment by bybai** [comment]
After polished based on comments, new unit test:
```
[root@bybc0602 postscripts]# updatenode bybc0609 confignetwork
bybc0609: xcatdsklspost: downloaded postscripts successfully
bybc0609: Fri Jul 14 03:04:34 EDT 2017 Running postscript: confignetwork
bybc0609: [I]: All valid nics and device list:
bybc0609: [I]: bond0 eth2@eth3
bybc0609: [I]: NetworkManager is inactive.
bybc0609: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
bybc0609: configure nic and its device : bond0 eth2@eth3
bybc0609: [I]: create_bond_interface ifname=bond0 slave_ports=eth2,eth3
bybc0609: [I]: Pickup xcatnet, "30_5_0_0-255_255_0_0", from NICNETWORKS for interface "bond0".
bybc0609: [W]: There is no MTU configured for network 30_5_0_0-255_255_0_0 in networks table.
bybc0609: [I]: ip link set bond0 down
bybc0609: [I]: [bond.down] >> 20: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
bybc0609: [I]: [bond.down] >>     link/ether ba:15:31:dc:56:52 brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: [bond.slavesAft] >>
bybc0609: [I]: ip link set eth2 down
bybc0609: [I]: [slave]: >> 4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
bybc0609: [I]: [slave]: >>     link/ether 42:47:0a:05:6a:09 brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: create_persistent_ifcfg ifname=eth2 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
bybc0609: ['ifcfg-eth2']
bybc0609: [I]: >> DEVICE="eth2"
bybc0609: [I]: >> BOOTPROTO="none"
bybc0609: [I]: >> NAME="eth2"
bybc0609: [I]: >> ONBOOT="yes"
bybc0609: [I]: >> USERCTL="no"
bybc0609: [I]: >> TYPE="Ethernet"
bybc0609: [I]: >> SLAVE="yes"
bybc0609: [I]: >> MASTER="bond0"
bybc0609: [I]: ip link set eth3 down
bybc0609: [I]: [slave]: >> 5: eth3: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
bybc0609: [I]: [slave]: >>     link/ether 42:82:0a:05:6a:09 brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: create_persistent_ifcfg ifname=eth3 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none
bybc0609: ['ifcfg-eth3']
bybc0609: [I]: >> DEVICE="eth3"
bybc0609: [I]: >> BOOTPROTO="none"
bybc0609: [I]: >> NAME="eth3"
bybc0609: [I]: >> ONBOOT="yes"
bybc0609: [I]: >> USERCTL="no"
bybc0609: [I]: >> TYPE="Ethernet"
bybc0609: [I]: >> SLAVE="yes"
bybc0609: [I]: >> MASTER="bond0"
bybc0609: [I]: [bond.slavesNew] >> eth2 eth3
bybc0609: [I]: ip link set bond0 up
bybc0609: [I]: [ip.link] >> 20: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT qlen 1000
bybc0609: [I]: [ip.link] >>     link/ether 42:47:0a:05:6a:09 brd ff:ff:ff:ff:ff:ff
bybc0609: [I]: create_persistent_ifcfg ifname=bond0 xcatnet=30_5_0_0-255_255_0_0 inattrs=ONBOOT=yes,USERCTL=no,TYPE=Bond,BONDING_MASTER=yes,BONDING_OPTS='mode=802.3ad miimon=100',BOOTPROTO=none,DHCLIENTARGS='-timeout 200'
bybc0609: [W]: There is no netmask configured for network 30_5_0_0-255_255_0_0 in networks table
bybc0609: ['ifcfg-bond0']
bybc0609: [I]: >> DEVICE="bond0"
bybc0609: [I]: >> BOOTPROTO="none"
bybc0609: [I]: >> IPADDR="30.5.106.9"
bybc0609: [I]: >> NAME="bond0"
bybc0609: [I]: >> BONDING_MASTER="yes"
bybc0609: [I]: >> ONBOOT="yes"
bybc0609: [I]: >> USERCTL="no"
bybc0609: [I]: >> TYPE="Bond"
bybc0609: [I]: >> BONDING_OPTS="mode=802.3ad miimon=100"
bybc0609: [I]: >> DHCLIENTARGS="-timeout 200"
bybc0609: postscript: confignetwork exited with code 0
bybc0609: Running of postscripts has completed.
```

**Comment by robin2008** [comment]
Fine with the changes, 
1, no need to warn MTU when it is not set as it is not common parameters.
2,netmask should be always there, we need ERROR message for it.
