### PR TITLE
fix #1157, enhance rinstall command

### LINKED ISSUE #1157: [customer] rinstall command does not support kvm node.
MN - SLES11.3 x86_64 xCAT 2.11.1 (grabbed Monday 16 May)
CN - SLES11.3 x86_64 KVM hypervisor hosted VM

This is something I haven't encountered before upgrading to 2.11.1, this is a known good cluster, with MN upgraded in place from 2.7.5. I made no chages to the xCAT tables (aside from creating new osiamages with more menomic names), and have restarted xcatd several times. Issue is when I run rinstall command, I get hte following errors:

# rinstall z10037
z10037: install sles11.3-x86_64-EI.kvm.sles11
z10037: Unable to identify plugin for this command, check relevant tables: nodehm.power,mgt;nodehm.mgt
Error: rsetboot failed on certain nodes.
Error: rinstall plugin bug, pid 6858, process description: 'xCATd SSL: rinstall to z10037 for root@localhost: rinstall instance: kvm instance' with error 'Died at /opt/xcat/sbin/xcatd line 1837.
' while trying to fulfill request for the following nodes: z10037

And the VM reboots and install starts anyway... Node definition below, slightly sanitized

# lsdef z10037
Object name: z10037
arch=x86_64
currchain=boot
currstate=boot
groups=compute,all
initrd=xcat/osimage/sles11.3-x86_64-install-EI-kvm/initrd
installnic=eth0
ip=172.31.253.184
kcmdline=quiet autoyast=nfs://z10000e1:/install/autoinst/z10037 install=nfs://z10000e1:/install/sles11.3/x86_64/1 netdevice=eth0 console=tty0 console=ttyS0,115200
kernel=xcat/osimage/sles11.3-x86_64-install-EI-kvm/linux
mac=42:8b:ac:1f:fd:b8
mgt=kvm
netboot=pxe
nfsserver=z10000e1
nodetype=osi
os=sles11.3
postbootscripts=otherpkgs,500EI_All,520EI_SLES11,599EI_All
postscripts=syslog,syncfiles,remoteshell
power=kvm
primarynic=eth0
profile=EI.kvm.sles11
provmethod=sles11.3-x86_64-install-EI-kvm
serialport=0
serialspeed=115200
status=booted
statustime=05-19-2016 00:40:51
vmcpus=2
vmhost=z1vmm99
vmmemory=2048
vmnics=br600=virtio
vmstorage=/gpfs/vmmdisks/rootvg/z10037_rootvg.img
vmstoragemodel=virtio

### PR DESCRIPTION
**Pull request by penguhyang**
fix #1157

### CODE REVIEW

File: xCAT-server/lib/xcat/plugins/kvm.pm [hunk 1]
```diff
@@ -3035,7 +3035,7 @@ sub power {
     unless ($retstring =~ /reset/) {
         $retstring = $retstring . getpowstate($dom);
     }
-    return (0, $retstring);
+    return $retstring;
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/kvm.pm]: why make this change?

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 2]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+            else {
+                foreach my $line (@$res) {
+                    $rsp->{data} ->[0] = $line;
+                    xCAT::MsgUtils->message("I", $rsp, $callback);
+                }
+            }
+            # We got an error with the rnetboot
+            if ($rc != 0) {
+                my $rsp = {};
+                $rsp->{error}->[0] = "rnetboot failed on certain nodes.";
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: please output the failed nodes list

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 3]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
-       $subreq, -1, 1);
-
-    $rc = $::RUNCMD_RC;
-    # fix output it is a hash and you must get error out of the hash.               
-    my $rsp = {};
-    foreach my $line (@$res) {
-        $rsp->{data} ->[0] = $line;
-        xCAT::MsgUtils->message("I", $rsp, $callback);
+    # We got an error with the nodeset
+    if ($rc != 0) {
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: have you filtered out the failed nodeS?

Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: Yes, it was filtered out before running nodeset command.

File: xCAT-server/lib/xcat/plugins/kvm.pm (hunk 1 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/kvm.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 4]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+
+    if ($command =~ /rinstall/) {
+        my $state = $ARGV[0];
+        my $reststates;
+        ($state, $reststates) = split (/,/, $state, 2);
+        chomp($state);
+        if ($state =~ /^install[=\$]/ or $state eq 'install' or $state =~ /^netboot[=\$]/ or $state eq 'netboot' or $state eq "image" or $state eq "winshell" or $state =~ /^osimage/ or $state =~ /^statelite/) {
+            my $target;
+            my $action;
+            if ($state =~ /=/) {
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: why so many states besides "osimage"?

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 5]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+            } else {
+                if ($state =~ /:/) {
+                    ($state, $action) = split ':',$state,2;
+                }
+            }
+            if ($state eq 'osimage') {
+                $OSIMAGE = $target;
+            }
+        } else {
+            unless ($state =~ /-/) {
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: what's this for?

Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: used for verify the options is not beginning with ``-`` or ``--``.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 4 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: used for capture the osimage.

Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: used for capture the osimage.

Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: please list all the arguments that rinstall supports. and remove all the unexpected arguments here

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 6]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+    if ($OSIMAGE) {
 
         # -O|--osimage is specified, ignore any -a,-p,-o options,
         # call "nodeset ... osimage= ..." to set the boot state of the noderange to the specified osimage,
-        # "nodeset" will handle the updating of node attributes such as os,arch,profile,provmethod
-        # verify input
+        # "nodeset" will handle the updating of node attributes such as os,arch,profile,provmethod.
+
+        # Verify input
         &checkoption("[-O|--osimage] $OSIMAGE",$OSVER,$PROFILE,$ARCH,$callback);
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: "-O" is not supported ,

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 7]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
-    if ($rc != 0)   # we got an error with the rsetboot
-    {
-       my $rsp = {};
-       $rsp->{error}->[0] = "rsetboot failed on certain nodes.";
-       xCAT::MsgUtils->message("E", $rsp, $callback);
+    # Group the nodes according to the nodehm.mgt
+    my %mnhash;
+    my $tabhm = xCAT::Table->new("nodehm");
+    foreach (@$nodes) {
+        my $nhhash = $tabhm->getNodeAttribs($_, ['mgt']);
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: should use getNodesAttribs

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 8]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
-       $rsp->{error}->[0] = "rpower failed on certain nodes.";
-       xCAT::MsgUtils->message("E", $rsp, $callback);
+    $tabhm->close();
+    # Now for each group based on mgt
+    foreach my $hmkey (keys %mnhash) {
+        $::RUNCMD_RC =0;
+        my $nodes = join(',', @{$mnhash{$hmkey}});
+        unless (($hmkey =~ /^hmc$/) or ($hmkey =~ /^ipmi$/) or ($hmkey =~ /^kvm$/)) {
+            my $rsp = {};
+            $rsp->{error}->[0] = "$nodes: rinstall only support nodehm.mgt type 'hmc', 'ipmi', 'kvm' at present time.";
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: should be ``rinstall only support nodehm.mgt type 'hmc', 'ipmi',the following nodes will be ignored:\n"$nodes"``

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 2 above)
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: should better be ``rnetboot failed on the following nodes: \n $nodes``

Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: you'd better parse the output of rnetboot, then filter out the failed nodes

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 9]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+            if ($rc != 0) {
+                my $rsp = {};
+                $rsp->{error}->[0] = "rnetboot failed on certain nodes.";
+                xCAT::MsgUtils->message("E", $rsp, $callback);
+                return 1;
+            }
+        }
+        else {
+            # Call "rsetboot" to set the boot order of the nodehm.mgt=ipmi nodes
+            if ($hmkey =~ /^ipmi$/) {
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: use ``elsif`` instead of ``else{if{``

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 10]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+                # Run rsetboot $noderange net
+                my @rsetbootarg;
+                push @rsetbootarg, "net";
+                push @rsetbootarg, "-u";
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: ``-u`` should not be the default option, it can be specified as an option for ``rinstall``

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 11]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+            else {
+                foreach my $line (@$res) {
+                    $rsp->{data} ->[0] = $line;
+                    xCAT::MsgUtils->message("I", $rsp, $callback);
+                }
+            }
+            # We got an error with the rpower
+            if ($rc != 0) {
+                my $rsp = {};
+                $rsp->{error}->[0] = "rpower failed on certain nodes.";
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: should better be ``rpower failed on the following nodes: \n $nodes``

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 12]
```diff
@@ -59,341 +55,560 @@ sub process_request
...
+                else {
+                    foreach my $line (@$res) {
+                        $rsp->{data} ->[0] = $line;
+                        xCAT::MsgUtils->message("I", $rsp, $callback);
+                    }
+                }
+                # We got an error with the rsetboot
+                if ($rc != 0) {
+                    my $rsp = {};
+                    $rsp->{error}->[0] = "rsetboot failed on certain nodes.";
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: should better be ``rsetboot failed on the following nodes: \n $nodes``

File: xCAT-server/lib/xcat/plugins/kvm.pm [hunk 13]
```diff
@@ -4039,7 +4039,7 @@ sub dohyp {
             }
             $text =~ s/^\s+//;
             $text =~ s/\s+$//;
-            $output{node}->[0]->{errorcode} = [$rc];
+            $output{node}->[0]->{errorcode}->[0] = [$rc];
```
Comment (chenglch) [inline xCAT-server/lib/xcat/plugins/kvm.pm]: Is there any conflict happens when you modify this line?
I meet an error when I use runxcmd to power on the kvm node about two weeks ago, so I change
 
    $output{node}->[0]->{errorcode} = $rc;  --> $output{node}->[0]->{errorcode} = [$rc];

Can you explain the reason to change this line?

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 12 above)
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: should parse the output of rsetboot and filter out the failed nodes

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 11 above)
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: should parse  the output of rpower and filter out the failed nodes

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 8 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 9 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: use else{if{ can make code more concise.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 6 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.
add verification before use function.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 2 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 12 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 11 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/kvm.pm (hunk 13 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/kvm.pm]: I didn't find any conflict happens after modify this line.
The runxcmd may call runxcmd_output, this line was defined in runxcmd_output function:
``
if (ref(\($node->{errorcode}->[0])) eq 'SCALAR')
``
So add ``->[0]`` to make the reference right.

Comment (chenglch) [inline xCAT-server/lib/xcat/plugins/kvm.pm]: `[$rc]` is already an array reference, so `$node->{errorcode}->[0]` is $rc

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 10 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 14]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+            my $rsp = {};
+            $rsp->{error}->[0] = "$OSIMAGE 'osarch' attribute not defined in 'osimage' table.";
+            xCAT::MsgUtils->message("E", $rsp, $callback);
+            return 1;
+        }
+        my $osimagearch = $ref->{osarch};
+        my $netbootval=xCAT::Utils->lookupNetboot($ref->{osvers},$ref->{osarch},$ref->{imagetype});
+        my @validnodes;
+        foreach (@$nodes) {
+            my $nrhash = $noderestable->getNodeAttribs($_, ['netboot']);
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: please get "netboot" and "arch" in one getNodeAttribs call

File: xCAT-server/lib/xcat/plugins/kvm.pm (hunk 13 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/kvm.pm]: So we have met the same problem, I will discard my fix.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 14 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: it's ok to separate them as they comes from different tables.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 15]
```diff
@@ -405,44 +649,46 @@ sub rinstall
...
     my $command = shift;
     my $callback = shift;
     my $rsp = {};
-    $rsp->{data}->[0] = "$command usage:";
+    $rsp->{data}->[0] = "Usage:";
     if ($command =~ /rinstall/) {
-      $rsp->{data}->[1] = " [-O|--osimage] [-c|--console] <noderange>";
-    } else {  # wininstall
-      $rsp->{data}->[1] = " [-O|--osimage] <noderange>";
+        $rsp->{data}->[1] = "   rinstall <noderange> [shell|boot|runcmd=bmcsetup|iscsiboot|osimage[=<imagename>]|offline|shutdown|stat]";
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: I prefer the usage info could be:

~~~~
rinstall <noderange> boot | shell | runcmd=bmcsetup [-c|--console] [-u|--uefimode] [-V|--verbose]
rinstall <noderange> osimage=<imagename> | -o imagename [--noupdateinitrd] [--ignorekernelchk] [-c|--console] [-u|--uefimode] [-V|--verbose]
~~~~

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 16]
```diff
@@ -405,44 +649,46 @@ sub rinstall
...
+        $rsp->{data}->[2] = "   rinstall <noderange> [osimage[=<imagename>]] [--noupdateinitrd] [--ignorekernelchk] [-c|--console] [-u|--uefimode] [-V|--verbose]";
+        $rsp->{data}->[3] = "   rinstall [-h|--help|-v|--version]";
+    }
+    else {
+        # winstall
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: I'd like to remove the ``-o -p -a`` support. The parameter should be same as ``rinstall``

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 17]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
-    {
-        &usage($command,$callback);
-        return 1;
+
+    if ($command =~ /rinstall/) {
+        my $state = $ARGV[0];
+        my $reststates;
+        ($state, $reststates) = split (/,/, $state, 2);
+        chomp($state);
+        if ($state =~ /^install[=\$]/ or $state eq 'install' or $state =~ /^netboot[=\$]/ or $state eq 'netboot' or $state eq "image" or $state eq "winshell" or $state =~ /^osimage/ or $state =~ /^statelite/) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: please remove the ``install|netboot|statelite``, it has been obsoleted from ``nodeset`` command.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 18]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+        } else {
+            unless ($state =~ /-/) {
+                $STATES = $state;
+            }
+        }
+
+        Getopt::Long::Configure("bundling");
+        Getopt::Long::Configure("no_pass_through");
+        unless (
+            GetOptions ('noupdateinitrd' => \$noupdateinitrd,
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: I'd like the rinstall and rinstall use the same options

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 19]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+            &checkoption("[-O|--osimage] $OSIMAGE",$OSVER,$PROFILE,$ARCH,$callback);
+        }
+
+        my $noderestable = xCAT::Table->new("noderes");
+        my $nodetypetable = xCAT::Table->new("nodetype");
+        my $osimagetable = xCAT::Table->new("osimage");
+        (my $ref) = $osimagetable->getAttribs({imagename => $OSIMAGE}, 'provmethod', 'osvers', 'profile', 'osarch','imagetype');
+        unless (defined($ref->{osarch})) {
+            my $rsp = {};
+            $rsp->{error}->[0] = "$OSIMAGE 'osarch' attribute not defined in 'osimage' table.";
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: please set the ``errorcode`` for $rsp hash when using the {error} key.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 20]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+            return 1;
+        }
+        my $osimagearch = $ref->{osarch};
+        my $netbootval=xCAT::Utils->lookupNetboot($ref->{osvers},$ref->{osarch},$ref->{imagetype});
+        my @validnodes;
+        foreach (@$nodes) {
+            my $nrhash = $noderestable->getNodeAttribs($_, ['netboot']);
+            unless (defined($nrhash) and defined($nrhash->{'netboot'})) {
+                my $rsp = {};
+                $rsp->{error}->[0] = "$_: 'netboot' attribute not defined in 'noderes' table.";
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: user just needs to care the ``netboot`` attribute for node is not set, but does not care which table the attribute is located. 
So the error message can be:
``Missing the 'netboot' attribute.``

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 21]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+        unless (defined($ref->{osarch})) {
+            my $rsp = {};
+            $rsp->{error}->[0] = "$OSIMAGE 'osarch' attribute not defined in 'osimage' table.";
+            xCAT::MsgUtils->message("E", $rsp, $callback);
+            return 1;
+        }
+        my $osimagearch = $ref->{osarch};
+        my $netbootval=xCAT::Utils->lookupNetboot($ref->{osvers},$ref->{osarch},$ref->{imagetype});
+        my @validnodes;
+        foreach (@$nodes) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: Please access table once to get all the attributes for all the nodes. Then using the result in memory.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 22]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+            my $nrhash = $noderestable->getNodeAttribs($_, ['netboot']);
+            unless (defined($nrhash) and defined($nrhash->{'netboot'})) {
+                my $rsp = {};
+                $rsp->{error}->[0] = "$_: 'netboot' attribute not defined in 'noderes' table.";
+                xCAT::MsgUtils->message("E", $rsp, $callback);
+                next;
+            }
+            else {
+                unless($netbootval =~ /$nrhash->{'netboot'}/i){
+                    $callback->({warning=> [join(",",@{$req->{node}}).": $nrhash->{'netboot'} might be invalid when provisioning $OSIMAGE,valid options: \"$netbootval\". \nFor more details see the 'netboot' description in the output of \"tabdump -d noderes\"."]});
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: confusing, you just tested one node has problem, why do you said all the nodes ``@{$req->{node}}`` has problem ?

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 23]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+                my $rsp = {};
+                $rsp->{error}->[0] = "$_: 'arch' attribute not defined in 'nodetype' table.";
+                xCAT::MsgUtils->message("E", $rsp, $callback);
+                next;
+            }
+            my $nodetypearch = $nthash->{'arch'};
+            if ($nodetypearch ne $osimagearch) {
+                unless ((($nodetypearch =~ /ppc64le/) or ($nodetypearch =~ /ppc64el/)) and (($osimagearch =~ /ppc64le/) or ($osimagearch =~ /ppc64el/))) {
+                    my $rsp = {};
+                    $rsp->{error}->[0] = "$_: 'arch' attribute value not same with $OSIMAGE 'osarch' attribute value.";
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: The message can be changed to:
The value of arch attribute is not same as the osarch attribute for osimage.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 24]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+            $subreq, -1, 1);
+
+        $rc = $::RUNCMD_RC;
         my $rsp = {};
-        foreach my $line (@$res) {
-            $rsp->{data} ->[0] = $line;
-            xCAT::MsgUtils->message("I", $rsp, $callback);
-        }      
+        if ($rc == 0) {
+            if ($VERBOSE) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: for the verbose output, we also need to display the command we are calling:
~~~~
Run command: nodeset <noderange> osimage=xxxx
~~~~

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 25]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+                foreach my $line (@$res) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: you can use following command to skip the for loop
~~~~
push @{$rsp->{data}}, @$res;
xCAT::MsgUtils->message("I", $rsp, $callback);
~~~~

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 26]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+        }
     }
-    else
-    {
+    elsif ($STATES) {
+        # Run nodeset $noderange $parameter
+        my @parameter;
+        push @parameter,"$STATES";
+        my $res =
+            xCAT::Utils->runxcmd(
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: For all the three cases: 1. with osimage=xxx 2. shell,boot ... 3. no parameter, the final action is same that running the ``nodeset`` command. So please prepare the arguments for the three cases and run ``nodeset`` at end

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 27]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+        # Now for each group based on provmethod
+        foreach my $key (keys %pnhash) {
             $::RUNCMD_RC =0;
             my $nodes = join(',', @{$pnhash{$key}});
-            if ($key =~ /^(install|netboot|statelite)$/)
-            {
-
-                # nodetype.provmethod = [install|netboot|statelite]
+            # If nodetype.provmethod = [install|netboot|statelite]
+            if ($key =~ /^(install|netboot|statelite)$/) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: if the key is ``install|netboot|statelite``, we can just print an error message as ``nodeset`` does. 

~~~~
# nodeset test1 install

Error: The options "install", "netboot", and "statelite" have been deprecated, use "nodeset <noderange> osimage=<osimage_name>" instead.
~~~~

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 3 above)
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: But some nodes might fail in the ``nodeset`` command, so you have to check the result of ``nodeset`` command for each node and filter out the failed nodes.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 28]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
-    {
-       my $rsp = {};
-       $rsp->{error}->[0] = "rpower failed on certain nodes.";
-       xCAT::MsgUtils->message("E", $rsp, $callback);
+    $tabhm->close();
+    # Now for each group based on mgt
+    foreach my $hmkey (keys %mnhash) {
+        $::RUNCMD_RC =0;
+        my $nodes = join(',', @{$mnhash{$hmkey}});
+        unless (($hmkey =~ /^hmc$/) or ($hmkey =~ /^ipmi$/) or ($hmkey =~ /^kvm$/)) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: The valid values for ``mgt`` can be : ipmi, blade, hmc, ivm, fsp, bpa, kvm, esx, rhevm. We should support all of them except the ``bpa``.
``ivm`` and ``fsp`` should have similar operation process as ``hmc``
``esx`` and ``rhevm`` should have similar operation process as ``kvm``
``blade`` should be same as ``kvm`` since we prefer the user has run the ``rbootseq`` command to set the boot order for the compute node before running ``rinstall``.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 29]
```diff
@@ -59,341 +55,589 @@ sub process_request
...
+            if ($rc == 0) {
+                if ($VERBOSE) {
+                    foreach my $line (@$res) {
+                        $rsp->{data} ->[0] = $line;
+                        xCAT::MsgUtils->message("I", $rsp, $callback);
+                    }
+                }
+            }
+            else {
+                foreach my $line (@$res) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: In the else {} block, it means ``($rc != 0)``. why we still have a ``($rc != 0)`` block afterward?

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 21 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.
use getNodesAttribs instead of getNodeAttribs.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 7 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 23 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 20 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 25 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 29 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 21 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 26 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 3 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 18 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 16 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 15 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 24 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 17 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 27 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 22 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 28 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

**Comment by gurevichmark** [comment]
I have 3 comments:

1. Some time ago Xiao Peng suggested we remove `iscsiboot` option from `nodeset` command documentation. I think it should not be exposed as an option to `rinstall` either:
_
_Hi Mark,
I took a quick look but could not find a clear procedure to use the iscsiboot. There is a doc in the SF to describe how to use iscsiboot for rh5.3, but it's hard to follow. The doc was not updated after the first creating in 2009. So I think no one is using it now. Then I suggest to remove this option from nodeset command._
_

2. Does it make sense to expose `offline` option? I think the purpose of this option it to put node into such a state that a discovery can be performed on it again. It seems to me the `offline` option is opposite of that `rinstall` tries to do and might be confusing to the user ?

3. The Synopsis section shows that `-c | --console` option can only be used when `osimage` is specified. But Example 3 at the end of the man page, shows `-c` used with no `osimage` specified.

**Comment by daniceexi** [comment]
I agree with the #1 and #2. I have pointed that out to YangPeng in my comments. Thanks Mark.
 
ThanksBest Regards----------------------------------------------------------------------Wang Xiaopeng (王晓朋)IBM China System Technology LaboratoryTel: 86-10-82453455Email: wxp@cn.ibm.comAddress: 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District Beijing P.R.China 100193
 
 
----- Original message -----From: Mark Gurevich <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Xiao Peng Wang/China/IBM@IBMCN, Comment <comment@noreply.github.com>Subject: Re: [xcat2/xcat-core] fix #1157, enhance rinstall command (#1280)Date: Thu, Jun 23, 2016 9:53 PM 
I have 3 comments:
                Some time ago Xiao Peng suggested we remove iscsiboot option from nodeset command documentation. I think it should not be exposed as an option to rinstall either:        _        Hi Mark,        I took a quick look but could not find a clear procedure to use the iscsiboot. There is a doc in the SF to describe how to use iscsiboot for rh5.3, but it's hard to follow. The doc was not updated after the first creating in 2009. So I think no one is using it now. Then I suggest to remove this option from nodeset command.        _                        Does it make sense to expose offline option? I think the purpose of this option it to put node into such a state that a discovery can be performed on it again. It seems to me the offline option is opposite of that rinstall tries to do and might be confusing to the user ?                        The Synopsis section shows that -c | --console option can only be used when osimage is specified. But Example 3 at the end of the man page, shows -c used with no osimage specified.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 19 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 30]
```diff
@@ -47,353 +45,513 @@ sub handled_commands
...
+        my $nodetypetable = xCAT::Table->new("nodetype");
+        my $nodehmtable = xCAT::Table->new("nodehm");
+        my $osimagetable = xCAT::Table->new("osimage");
+        (my $ref) = $osimagetable->getAttribs({imagename => $OSIMAGE}, 'osvers', 'osarch','imagetype');
+        unless (defined($ref->{osarch})) {
+            my $rsp = {};
+            $rsp->{error}->[0] = "$OSIMAGE 'osarch' attribute not defined in 'osimage' table.";
+            $rsp->{errorcode}->[0] = 1;
+            xCAT::MsgUtils->message("E", $rsp, $callback);
+            return 1;
```
Comment (immarvin) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: the table handlers should be closed here

Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 31]
```diff
@@ -47,353 +45,511 @@ sub handled_commands
...
-       my $rsp = {};
-       $rsp->{error}->[0] = "rsetboot failed on certain nodes.";
-       xCAT::MsgUtils->message("E", $rsp, $callback);
+    else {
+        # We got an error with the nodeset
+        my @successnodes;
+        my @failurenodes;
+        foreach my $line (@$res) {
+            $rsp->{data} ->[0] = $line;
+            if ($line =~ /: install/) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: How about for diskless or satelite node?

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 32]
```diff
@@ -47,353 +45,511 @@ sub handled_commands
...
+            }
+            xCAT::MsgUtils->message("I", $rsp, $callback);
+        }
+        foreach my $node (@nodes) {
+            if ($nodes{$node} = 1) {
+                push @failurenodes, $node;
+            }
+        }
+        my $rsp = {};
+        $rsp->{error}->[0] = "nodeset failed on the following nodes: \n @failurenodes";
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: please change the message to: failed to run nodeset against the following nodes:

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 33]
```diff
@@ -47,353 +45,511 @@ sub handled_commands
...
+                            push @failurenodes, $node;
+                        }
+                    }
+                    my $rsp = {};
+                    $rsp->{error}->[0] = "rsetboot failed on the following nodes: \n @failurenodes";
+                    $rsp->{errorcode}->[0] = 1;
+                    xCAT::MsgUtils->message("E", $rsp, $callback);
+                    @nodes = @successnodes;
+                    foreach my $node (@nodes) {
+                        $nodes{$node} = 0;
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: make the code be consistent with L310 that 0 is failure or success

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 34]
```diff
@@ -47,353 +45,511 @@ sub handled_commands
...
+                    push @{$rsp->{data}}, @$res;
+                    xCAT::MsgUtils->message("I", $rsp, $callback);
+                }
+            }
+            else {
+                # We got an error with the rpower
+                my @failurenodes;
+                foreach my $line (@$res) {
+                    $rsp->{data} ->[0] = $line;
+                    if ($line =~ /: on reset/) {
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: is ``on reset`` used to check the reset? how about to boot from off?

File: xCAT-server/lib/xcat/plugins/rinstall.pm [hunk 35]
```diff
@@ -47,353 +45,511 @@ sub handled_commands
...
-               my $rsp = {};
-               $rsp->{error}->[0] = "rinstall -c only accepts one node in the noderange. See winstall for support for support of consoles on multiple nodes.";
+    # Check if they asked to bring up a console (-c) from rinstall always for winstall
+    $req->{startconsole}->[0] = 0;
+    if ($command =~ /rinstall/) {
+        # For rinstall, the -c|--console option can provide the remote console for only 1 node
+        if ($CONSOLE) {
+            if (scalar @nodes != 1) {
+                my $rsp = {};
+                $rsp->{error}->[0] = "rinstall -c only accepts one node in the noderange. See winstall for support for support of consoles on multiple nodes.";
```
Comment (daniceexi) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: ??
See winstall for support for support of consoles on multiple nodes

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 32 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 31 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 34 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 35 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

File: xCAT-server/lib/xcat/plugins/rinstall.pm (hunk 33 above)
Comment (penguhyang) [inline xCAT-server/lib/xcat/plugins/rinstall.pm]: fixed.

**Comment by daniceexi** [comment]
I have reviewed the change and agree to merge.
